services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - blog-data:/var/www/html/Data
      - blog-uploads:/var/www/html/public/uploads
    environment:
      - APP_ENV=local

volumes:
  blog-data:
  blog-uploads: