server {
    listen 80;
    server_name localhost;
    index public/index.php;
    error_log c:/nginx/logs/localhost.error.log;
    access_log c:/nginx/logs/localhost.access.log;
    root /var/www/html/public;

    location ~ \.php$ {
    fastcgi_pass app:9000; 
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}

}